version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: /bin/bash -c "/usr/src/app/start-project.sh"
    volumes:
      - .:/usr/src/app
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://admin:senha@db:5432/alvos_db
      - DEBUG=True
    networks:
      - join_network

  db:
    image: postgres:latest
    container_name: django-db
    environment:
      POSTGRES_DB: alvos_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - join_network

volumes:
  postgres_data:

networks:
  join_network:
    driver: bridge
